services:
    phlexible_indexer_media.document_applier:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\DocumentApplier\ChainDocumentApplier
        public: false
        arguments:
            -
                - "@phlexible_indexer_media.base_document_applier"
                - "@phlexible_indexer_media.meta_document_applier"
                - "@phlexible_indexer_media.content_document_applier"

    phlexible_indexer_media.base_document_applier:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\DocumentApplier\BaseDocumentApplier
        public: false
        arguments:
            - "@event_dispatcher"
            - "@logger"


    phlexible_indexer_media.content_document_applier:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\DocumentApplier\ContentDocumentApplier
        public: false
        arguments:
            - "@phlexible_indexer_media.indexible_content_voter"
            - "@event_dispatcher"
            - "@logger"
        tags:
            - {name: monolog.logger, channel: indexer}

    phlexible_indexer_media.meta_document_applier:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\DocumentApplier\MetaDocumentApplier
        public: false
        arguments:
            - "@phlexible_media_manager.file_meta_set_resolver"
            - "@phlexible_media_manager.file_meta_data_manager"
            - "@event_dispatcher"
            - "@logger"
        tags:
            - {name: monolog.logger, channel: indexer}
