services:
    phlexible_indexer_media.media_content_identifier:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\MediaContentIdentifier
        arguments:
            - "@phlexible_media_manager.volume_manager"

    phlexible_indexer_media.media_document_builder:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\MediaDocumentBuilder
        arguments:
            - "@phlexible_indexer.document_factory"
            - "@phlexible_indexer_media.document_mapper"
            - "@phlexible_indexer_media.indexible_voter"
            - "@event_dispatcher"
            - "%phlexible_indexer_media.document_class%"
        tags:
            - {name: monolog.logger, channel: indexer}

    phlexible_indexer_media.media_indexer:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\MediaIndexer
        arguments:
            - "@phlexible_indexer_media.media_document_builder"
            - "@phlexible_indexer_media.storage"
            - "@phlexible_indexer_media.media_content_identifier"
            - "@phlexible_queue.job_manager"
            - "@event_dispatcher"
            - "@logger"
            - "%phlexible_indexer_media.batch_size%"
        tags:
            - {name: phlexible_indexer.indexer}
            - {name: monolog.logger, channel: indexer}

    # commands
    phlexible_indexer_media.command.add_all:
        class: Phlexible\Bundle\IndexerMediaBundle\Command\AddAllCommand
        arguments:
            - "@phlexible_indexer_media.media_indexer"
        tags:
            - {name: console.command}

    phlexible_indexer_media.command.add:
        class: Phlexible\Bundle\IndexerMediaBundle\Command\AddAllCommand
        arguments:
            - "@phlexible_indexer_media.media_indexer"
        tags:
            - {name: console.command}

    phlexible_indexer_media.command.delete:
        class: Phlexible\Bundle\IndexerMediaBundle\Command\AddAllCommand
        arguments:
            - "@phlexible_indexer_media.media_indexer"
        tags:
            - {name: console.command}

    phlexible_indexer_media.command.find:
        class: Phlexible\Bundle\IndexerMediaBundle\Command\FindCommand
        arguments:
            - "@phlexible_indexer_media.media_indexer"
        tags:
            - {name: console.command}

    # event listeners
    phlexible_indexer_media.listener.file:
        class: Phlexible\Bundle\IndexerMediaBundle\EventListener\FileListener
        arguments:
            - "@phlexible_indexer_media.media_indexer"
        tags:
            - {name: kernel.event_subscriber}
