services:
    phlexible_indexer_media.media_indexer:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\MediaIndexer
        arguments:
            - @phlexible_indexer_media.storage
            - @phlexible_indexer_media.media_document_mapper
            - @phlexible_queue.job_manager
            - @logger
        tags:
            - {name: phlexible_indexer.indexer}

    phlexible_indexer_media.media_document_mapper:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\MediaDocumentMapper
        arguments:
            - @phlexible_indexer.document_factory
            - @phlexible_media_extractor.extractor
            - @phlexible_media_type.media_type_manager
            - @phlexible_media_manager.volume_manager
            - @event_dispatcher
            - %phlexible_meta_set.languages.default%
        tags:
            - {name: phlexible_indexer.indexer}

    # event listeners
    phlexible_indexer_media.listener.file:
        class: Phlexible\Bundle\IndexerMediaBundle\EventListener\FileListener
        arguments: [@phlexible_queue.job_manager]
        tags:
            - {name: kernel.event_subscriber}
