services:
    indexermedia.indexer:
        class: Phlexible\IndexerMediaBundle\Indexer\MediaIndexer
        arguments:
            - "@event_dispatcher"
            - "@indexermedia.storage"
            - "@indexer.documentfactory"
            - "@mediaasset.extractor.content"
            - "@mediasite.manager"
            - "%metasets.languages.default%"
        tags:
            - {name: "indexer.indexer"}

    indexermedia.boost:
        class: Phlexible\IndexerMediaBundle\Boost\Boost

    indexermedia.query:
        class: Phlexible\IndexerMediaBundle\Query\MediaQuery
        arguments: ["@indexer.query.parser", "@indexermedia.boost"]
        tags:
            - {name: "indexer.search"}

    # event listeners
    indexermedia.listener.importfile:
        class: Phlexible\IndexerMediaBundle\EventListener\FileListener
        tags:
            - {name: "kernel.event_listener", event: media_site.import_file, method: onImportFile}

    indexermedia.listener.replacefile:
        class: Phlexible\IndexerMediaBundle\EventListener\FileListener
        tags:
            - {name: "kernel.event_listener", event: media_site.replace_file, method: onReplaceFile}

    indexermedia.listener.movefile:
        class: Phlexible\IndexerMediaBundle\EventListener\FileListener
        tags:
            - {name: "kernel.event_listener", event: media_site.move_file, method: onMoveFile}

    indexermedia.listener.deletefile:
        class: Phlexible\IndexerMediaBundle\EventListener\FileListener
        tags:
            - {name: "kernel.event_listener", event: media_site.delete_file, method: onDeleteFile}

    indexermedia.listener.savemeta:
        class: Phlexible\IndexerMediaBundle\EventListener\FileListener
        tags:
            - {name: "kernel.event_listener", event: media_manager.save_meta, method: onSaveMeta}

    indexermedia.listener.createdocument:
        class: Phlexible\IndexerMediaBundle\EventListener\CreateDocumentListener
        tags:
            - {name: "kernel.event_listener", event: indexer.create_document, method: onCreateDocument}
