services:
    phlexible_indexer_media.media_indexer:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\MediaIndexer
        arguments:
            - "@phlexible_indexer_media.storage"
            - "@phlexible_indexer_media.media_document_mapper"
            - "@phlexible_queue.job_manager"
            - "@logger"
            - "%phlexible_indexer_media.batch_size%"
        tags:
            - {name: phlexible_indexer.indexer}
            - {name: monolog.logger, channel: indexer}

    phlexible_indexer_media.media_document_mapper:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\MediaDocumentMapper
        arguments:
            - "@phlexible_indexer.document_factory"
            - "@phlexible_media_extractor.extractor"
            - "@phlexible_media_manager.volume_manager"
            - "@phlexible_media_type.media_type_manager"
            - "@phlexible_media_manager.file_meta_set_resolver"
            - "@phlexible_media_manager.file_meta_data_manager"
            - "@phlexible_indexer_media.indexible_voter"
            - "@phlexible_indexer_media.indexible_content_voter"
            - "@event_dispatcher"
            - "%phlexible_meta_set.languages.default%"

    phlexible_indexer_media.file_exists_indexible_voter:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\IndexibleVoter\FileExistsIndexibleVoter
        tags:
            - {name: phlexible_indexer_media.indexible_content_voter}

    phlexible_indexer_media.indexible_voter:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\IndexibleVoter\ChainIndexibleVoter
        arguments:
            - []

    phlexible_indexer_media.indexible_content_voter:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\IndexibleVoter\ChainIndexibleVoter
        arguments:
            - []

    # event listeners
    phlexible_indexer_media.listener.file:
        class: Phlexible\Bundle\IndexerMediaBundle\EventListener\FileListener
        arguments:
            - "@phlexible_indexer_media.media_indexer"
        tags:
            - {name: kernel.event_subscriber}
