services:
    phlexible_indexer_media.media_content_identifier:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\MediaContentIdentifier
        arguments:
            - "@phlexible_media_manager.volume_manager"

    phlexible_indexer_media.media_indexer:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\MediaIndexer
        arguments:
            - "@phlexible_indexer.document_factory"
            - "@phlexible_indexer_media.storage"
            - "@phlexible_indexer_media.media_document_mapper"
            - "@phlexible_indexer_media.media_content_identifier"
            - "@phlexible_queue.job_manager"
            - "@logger"
            - "%phlexible_indexer_media.document_class%"
            - "%phlexible_indexer_media.batch_size%"
        tags:
            - {name: phlexible_indexer.indexer}
            - {name: monolog.logger, channel: indexer}

    phlexible_indexer_media.media_document_mapper:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\MediaDocumentMapper
        arguments:
            - "@phlexible_indexer_media.indexible_voter"
            - "@phlexible_indexer_media.document_applier"
            - "@event_dispatcher"
            - "@logger"

    # event listeners
    phlexible_indexer_media.listener.file:
        class: Phlexible\Bundle\IndexerMediaBundle\EventListener\FileListener
        arguments:
            - "@phlexible_indexer_media.media_indexer"
        tags:
            - {name: kernel.event_subscriber}
