services:
    phlexible_indexer_media.indexer:
        class: Phlexible\Bundle\IndexerMediaBundle\Indexer\MediaIndexer
        arguments:
            - @event_dispatcher
            - @phlexible_indexer_media.storage
            - @phlexible_indexer.document_factory
            - @phlexible_media_asset.extractor.content
            - @phlexible_media_site.manager
            - %phlexible_meta_set.languages.default%
        tags:
            - {name: phlexible_indexer.indexer}

    phlexible_indexer_media.boost:
        class: Phlexible\Bundle\IndexerMediaBundle\Boost\MediaBoost

    phlexible_indexer_media.query:
        class: Phlexible\Bundle\IndexerMediaBundle\Query\MediaQuery
        arguments: [@phlexible_indexer.query.parser, @phlexible_indexer_media.boost]
        tags:
            - {name: phlexible_indexer.search}

    # event listeners
    phlexible_indexer_media.listener.file:
        class: Phlexible\Bundle\IndexerMediaBundle\EventListener\FileListener
        arguments: [@phlexible_queue.job_manager]
        tags:
            - {name: kernel.event_subscriber}
